### ISSUE TITLE
Import Fail CRM 2015 UR 0.1

### ISSUE THREAD

**Issue by skojhani** [rajyraman/Personal-View-to-System-View#1]
Dear Team,

we are trying to import this solution this solution in CRM 2015 UR 0.1 on premises. it is failing. kindly advise

Regards

**Comment by rajyraman** [comment]
This solution works only with CRM2016. I am working on a solution that uses the SOAP endpoint and will work with CRM2015. I will release it sometime next week.

**Comment by skojhani** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Thanks for tub quick response


Sent from Yahoo Mail for iPhone


On Tuesday, December 20, 2016, 9:40 PM, Natraj Yegnaraman <notifications@github.com> wrote:


This solution works only with CRM2016. I am working on a solution that uses the SOAP endpoint and will work with CRM2015. I will release it sometime next week.

**Comment by rajyraman** [comment]
CRM2015 managed solution now available for download in the release area. Please log any issues that you encounter. I have tested this only in Chrome and Firefox, so please let me know if you are using IE, when you log any issue. Thank you.

**Comment by skojhani** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Thanks. If I found any issue definitely I will let you know
Good Job 


Sent from Yahoo Mail for iPhone


On Wednesday, December 21, 2016, 3:36 AM, Natraj Yegnaraman <notifications@github.com> wrote:


Closed #1.
