### ISSUE TITLE
limit access to the promote button?

### ISSUE THREAD

**Issue by AnnemiekeHoogenboezem** [rajyraman/Personal-View-to-System-View#2]
Hi,

I like your tool to promote saved personal views to system views. It would save me and my super users a lot of time if they can build their system views themselves. However I would like to limit the use of it just to them. Is there a way that I can assign the use of it to only one security role?

**Comment by rajyraman** [comment]
The button only appears if the user has create privilege to savedquery entity. Below is the relevant line in the ribbon definition.

https://github.com/rajyraman/Personal-View-to-System-View/blob/6c96bda5e38c22755e4bb08c81af29cf8bcef4b4/userquery.ribbon.xml#L41-L45

You should be able to handle this using normal security roles.
