### ISSUE TITLE
Imported with warning - and not working

### ISSUE THREAD

**Issue by JensNormann** [rajyraman/Personal-View-to-System-View#4]
I have just imported the 8_2 version into a Dynamics online 2016. I got a warning regarding labels, disregarded og went on to publish. But I see no new button in advanced view. Is this because labels are not in danish, which is my langauge?

regards, 
Jens Nielsen

**Comment by rajyraman** [comment]
Did you click on the "Saved Views" tab?

![image](https://user-images.githubusercontent.com/5035266/35954466-e4f906ce-0cdd-11e8-8f5a-48a2f9d5e5a1.png)

**Comment by JensNormann** [comment]
I did.
![image](https://user-images.githubusercontent.com/36251726/35956957-149788aa-0c99-11e8-810b-0369e05b5009.png)

**Comment by JensNormann** [comment]
Oh, sorry - I see the button now, it's just the label that confused me!
